### ISSUE TITLE
Ansible warnings

### ISSUE THREAD

**Issue by jabl** [CSC-IT-Center-for-Science/ansible-role-smartd#4]
<pre><code>
TASK [ansible-role-smartd : debug] *********************************************
Tuesday 11 October 2016  10:11:02 +0300 (0:00:00.145)       0:00:05.181 ******* 
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this will be a fatal error.: 'dict object' has no attribute 'stdout_lines'.
This feature will be removed in a 
future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
skipping: [login2]

TASK [ansible-role-smartd : DELL - populate smartd file with these devices except /dev/sda] ***
Tuesday 11 October 2016  10:09:49 +0300 (0:00:00.136)       0:00:05.186 ******* 
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this will be a fatal error.: 'dict object' has no attribute 'stdout_lines'.
This feature will be removed in a 
future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
skipping: [login2]

TASK [ansible-role-smartd : Generic - populate smartd file with these devices] *
Tuesday 11 October 2016  10:09:49 +0300 (0:00:00.142)       0:00:05.329 ******* 
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this will be a fatal error.: 'dict object' has no attribute 'stdout_lines'.
This feature will be removed in a 
future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
skipping: [login2]
</code></pre>

**Comment by martbhell** [comment]
Thanks!

Think one can fix this by adding "ansible_devices.sda is defined"
